/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed": "#001443",
        "inverse-primary": "#006a71",
        "tertiary": "#9cb4fe",
        "error": "#ff716c",
        "inverse-surface": "#f7f9ff",
        "surface-bright": "#242d37",
        "surface-container-low": "#0d141b",
        "surface-container": "#131a22",
        "secondary-fixed-dim": "#ffb194",
        "tertiary-container": "#8ea6f0",
        "on-error-container": "#ffa8a3",
        "on-tertiary": "#143073",
        "tertiary-fixed-dim": "#89a1ea",
        "secondary-dim": "#ff7439",
        "surface": "#090f15",
        "tertiary-fixed": "#97aef8",
        "surface-container-high": "#182028",
        "primary-fixed": "#00eefc",
        "on-primary-fixed-variant": "#005e64",
        "on-secondary-fixed": "#611e00",
        "background": "#090f15",
        "on-background": "#e6ebf4",
        "surface-container-lowest": "#000000",
        "secondary": "#ff7439",
        "surface-dim": "#090f15",
        "secondary-container": "#a73a00",
        "outline": "#70767e",
        "primary-container": "#00eefc",
        "surface-tint": "#8ff5ff",
        "secondary-fixed": "#ffc4af",
        "inverse-on-surface": "#50565d",
        "on-secondary": "#3f1100",
        "on-secondary-fixed-variant": "#903100",
        "tertiary-dim": "#849be4",
        "on-primary-container": "#005359",
        "on-error": "#490006",
        "outline-variant": "#424850",
        "on-primary": "#005d63",
        "primary": "#8ff5ff",
        "on-primary-fixed": "#003f43",
        "error-dim": "#d7383b",
        "on-secondary-container": "#fff6f3",
        "surface-container-highest": "#1e272f",
        "surface-variant": "#1e272f",
        "error-container": "#9f0519",
        "on-tertiary-container": "#022568",
        "on-surface-variant": "#a6abb4",
        "primary-dim": "#00deec",
        "on-tertiary-fixed-variant": "#1a3577",
        "primary-fixed-dim": "#00deec",
        "on-surface": "#e6ebf4"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      fontFamily: {
        headline: ["Lexend", "sans-serif"],
        body: ["Inter", "sans-serif"],
      },
    },
  },
  plugins: [],
}
